### PR TITLE
Add Git based Index

### PR DESCRIPTION
**Pull request by r0mainK**
Pretty big PR implementing the Git based index:

**Breakdown of the changes:**

- [x] `main.py`: added functions for git index args (`remote_repo`, `username`, `password`) and template args `template_model` and `template_readme`; add `--force` to initialization parser so we can not destroy registry carelessely, added `--meta` keyword to `publish` parser in order to point towards a JSON that will contain all addtionnal information we may want to give (extras, etc). It is not necessary, I added a default JSON template to the repo that is mostly empty if the flag is not used.
- [x] `delete.py`/`dump.py`: moved code to `registry.py`, files were deleted
- [x] `gcs_backend.py`: took out `fetch_index` and `update_index`, added a helper function to create the GCS client since both `connect`and the new method `initialize_backend` use it and added/renamed some errors
- [x] `model.py`: small change, since backend and index are now separate I had to change a bit the logic to still make it possible to query with only the UUID, added an index dict param to the `load` function 
- [x] `models.py`: same story, added it in the constructor of `GenericModel`
- [x] `registry.py`: a lot of changes, however most of the logic is not here anymore, the functions almost only call backend/git_index methods. notable change: `list`does not require backend anymore
- [x] `storage_backend.py`: took out `fetch_index` and `update_index`, added `initialize_backend` and errors
-  [x] `templates/*`: contains the mebtionned above JSON template as well as jinja2 templates from `src-d/models`
-  [x] `setup.py`/`requirements.txt`: added `src-d/models` libs and line to add templates to the package
- [x]  `index.py`: new file that contains the `GitIndex`class now used to maintain the index. Incorporates the old functions of `src-d/models` as well as methods to fetch/upload the index, add/remove models, and initialize registries

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
OK, this is a bit too much for me :) 

Please split. I would suggest:

1. Readme and docs are the last
2. Templates and requirements are the first
3. `storage_backend.py` changes separate
4. The rest shall be splitted too - see what's the best way yourself

Amazing work btw, can't wait to have it merged.

**Comment by r0mainK** [comment]
Aha no problem, thks ^^ okay then I'll split in something like 5 or 6 PRs, then close this

**Comment by marnovo** [comment]
@r0mainK @vmarkovtsev what issue is this related to?

**Comment by vmarkovtsev** [comment]
@marnovo https://github.com/src-d/backlog/issues/1205

**Comment by r0mainK** [comment]
@marnovo this issue: https://github.com/src-d/backlog/issues/1205 

basically having the index of the registry on the backend was not great so now it's gonna be exclusively on github, e.g. https://github.com/src-d/models , and itll be updated with `modelforge` cmds.

**Comment by vmarkovtsev** [comment]
Closing - it was splitted.

**Comment by vmarkovtsev** [comment]
LOL

**Comment by r0mainK** [comment]
aha

**Comment by marnovo** [comment]
Thanks! Please let's always try to reference things around so people have more context of why/what is going one.

Idea for the future: intelligent PR splitter, to split large PRs into more manageable ones for review. ;)

**Pull request closed without merging**
