### PR TITLE
Fix fork hang while import modelforge.backends

### PR DESCRIPTION
**Pull request by zurk**
Here is the same problem occurred as in https://github.com/src-d/ast2vec/pull/50

you can check it with the same example from here https://github.com/bblfsh/python-driver/issues/55

just replace `import bblfsh` with `import modelforge.backends`

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
What? Can you prove this? I have never seen that this API started a background thread

**Comment by zurk** [comment]
Yes, I can. 
As I said, the same example: 
```python
import os
import sys
import time

import modelforge.backends
# And if you import just modelforge it will be fine

def func(n):
    print('Sleep during {} sec...'.format(n))
    time.sleep(n)
    return n

if __name__ == '__main__':
    for n in range(1, 3):
        pid = os.fork()
        if pid == 0:
            # if you do import bblfsh in this place everythink will be fine
            res = func(n)
            print('Sleep in is Done!')
            sys.exit(0)
        else:
            print('os.waitpid is waiting for {}...'.format(pid))
            _, status = os.waitpid(pid, 0)
            print('os.waitpid is fine!')
    print('ok, terminate.')
```

**Comment by vmarkovtsev** [comment]
This is awful. Please add the comment which explains why you had to move this import then.

**Comment by zurk** [comment]
Yes, I don't like it too.

There is a comment in my commit. 
Do you want something more?

**Comment by vmarkovtsev** [comment]
Oops, missed it

**Pull request merged**
