### PR TITLE
Change LICENSE to Apache v2.0 and update README.md

### PR DESCRIPTION
**Pull request by crweiner**
The README claims that Modelforge is licensed under Apache v2.0, but the actual license file is GNU GPL v3.0 inside the repo. 

If you meant to license under the GNU, then this PR fixes the readme to state the correct license, as well as provide a link to it in your repo.

If you meant to license under Apache v2.0, let me know and I will amend this PR to change the LICENSE file instead.

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
Wow thanks @crweiner for the check. We indeed meant Apache 2.0.

**Comment by crweiner** [comment]
No problem @vmarkovtsev! I've updated the title of this PR and changed the LICENSE file to Apache v2.0, as you originally intended.

**Comment by crweiner** [comment]
Humm...I see that my master fork wasn't up-to-date, so if this causes problems with Travis, let me know and I can delete this PR and start over... Sorry about that.

**Comment by vmarkovtsev** [comment]
That's fine. Thanks again! :beers: :maple_leaf:

**Pull request merged**
