### PR TITLE
Fix assemble_sparse_matrix

### PR DESCRIPTION
**Pull request by Guillemdb**
Signed-off-by: Guillem Duran <guillem@sourced.tech>

### CODE REVIEW

**Comment by Guillemdb** [comment]
In `assemble_sparse_matrix`, `subtree["data"]` is a tuple that contains 3 numpy arrays. 

As a tuple is an inmutable object, the assignment expression `subtree["data"][2] = indptr.cumsum()` raises an error. 

To avoid this problem, I suggest updating the values of the target array directly: `subtree["data"][2][:] = indptr.cumsum()`

**Comment by irinakhismatullina** [comment]
To fix the fail you need to pin the version of `pycodestyle` in requirements-lint.txt
```
pydocstyle==3.0.0 # remove when https://github.com/PyCQA/pydocstyle/issues/375 is solved
```

**Comment by zurk** [comment]
wow, how this code work before?
@Guillemdb can you please add a test that reproduces the error?

**Comment by vmarkovtsev** [comment]
The reason why the code worked before is because `subtree["data"]` is a list, not a tuple, and that's guaranteed by ASDF. The function is used in wrong way.

**Comment by vmarkovtsev** [comment]
So this PR should be changed to reflect that somehow in the documentation or in a type hit.

**Comment by vmarkovtsev** [comment]
We should also switch from tuples to lists in disassemble, so there is no confusion.

**Comment by vmarkovtsev** [comment]
Superseded by https://github.com/src-d/modelforge/pull/101

**Pull request closed without merging**
